version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    depends_on:
      - redis
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - "8000:8000"